### ISSUE TITLE
更改为担保交易

### ISSUE THREAD

**Issue by billie66** [happypeter/alipay_dualfun#7]
改为担保交易，只需要修改两个地方：

1. 把双功能接口名称 `trade_create_by_buyer` 改为担保交易的接口 `create_partner_trade_by_buyer` 

2. 发货接口的请求参数 `transport_type` 和 `create_transport_type` 两个参数不能同时为空

**Comment by happypeter** [comment]
双功能都没有了，所以我这个 Gem 应该宣布死亡了，改成用 rei 的 gem 吧
